# Generated by Django 5.1.5 on 2025-01-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
