# Generated by Django 5.1.5 on 2025-01-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_thumbnail_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
