# Generated by Django 5.1.5 on 2025-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=255, verbose_name='Variation Value'),
        ),
    ]
