# Generated by Django 5.1.5 on 2025-01-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_variation_variation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black')], max_length=255, verbose_name='Variation Value'),
        ),
    ]
